[workspace]
dependencies_update = true
pr_labels = ["release"]

[changelog]
commit_parsers = [
    { footer = "^Changelog: ?ignore", skip = true },
    { footer = "^Changelog: ?changed", group = "changed" },
    { message = "^feat", group = "added" },
    { message = "^deprecated", group = "deprecated" },
    { message = "^fix", group = "fixed" },
    { message = "^security", group = "security" },
    { message = "^refactor", skip = true },
    { message = "^release", skip = true },
    { message = "^chore", skip = true },
    { message = "^ci", skip = true },
    { message = "^.*", group = "other" },
]
