{{ if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "klag-exporter.fullname" . }}
  labels:
    {{- include "klag-exporter.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "klag-exporter.selectorLabels" . | nindent 8 }}
  endpoints:
    - port: http
      interval: 30s
      {{- with .Values.serviceMonitor.additionalEndpointConfig }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
  {{- with .Values.serviceMonitor.additionlConfig }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
{{ end }}
